services:
  - type: web
    name: the-battle-lab
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn analyzer.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8 